config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tasks#landing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  has_one :user
  
  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:landing]
  before_action :set_task, only: %i[ show edit update destroy ]

  def landing
  
  end
  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    if @task.save
      # turbo stream here notice: "Task was successfully created."
      render turbo_stream: turbo_stream.prepend("tasks", partial: 'tasks/task', locals: {task: @task})
    else
      render :new, status: :unprocessable_entity
      render @task.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    if @task.update(task_params)
      render turbo_stream: turbo_stream.replace(@task, partial: 'tasks/task', locals: {task: @task})
    else
      render :edit, status: :unprocessable_entity
      render @task.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    # I dont really want a redirect here !! stream
      redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :status)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  def create
    build_resource(sign_up_params)
    
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: tasks_url
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: tasks_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>TurboFramesPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav>
    <%= render 'shared/nav' %>
  </nav>

  <body>
  <div data-controller="messagehandler" >
    <p class="notice" id="notice"><%= notice %></p>
    <p class="alert" id="alert"><%= alert %></p>
  </div>

  <% if user_signed_in? %>
    <%= "logged in as: #{current_user.email} " %>
  <% end %>

  <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="bg-gray-800 py-4 px-8">
  <div class="flex justify-between items-center">
    <div class="flex items-center space-x-4">
      <a href="/" class="text-white text-xl font-bold">HOME</a>
    </div>
    <div class="flex space-x-4">
      <% if user_signed_in? %>
        <%= link_to 'LOGOUT', destroy_user_session_url, data: { turbo_method: :delete }, class: "text-white hover:text-gray-300" %>
        <%= link_to 'VIEW MY TASKS', tasks_url, class: "text-white hover:text-gray-300" %>
      <% else %>
        <%= link_to 'SIGN UP', new_user_registration_path, data: {turbo_frame: 'modal'}, class: "text-white hover:text-gray-300" %>
        <%= link_to 'SIGN IN', new_user_session_path, data: {turbo_frame: 'modal'}, class: "text-white hover:text-gray-300" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents") do |form| %>
  <div data-controller="taskhandler" class="fixed inset-0 flex items-center justify-center z-50 bg-gray-800 bg-opacity-50">
    <div class="bg-white w-full max-w-md rounded-lg shadow-lg p-8">
      <% if task.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul>
            <% task.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="font-bold">
        <% if form_type_needed == "new" %>
          <h1>Create New Task</h1>
        <% elsif form_type_needed == "edit" %>
          <h1>Edit This Task</h1>
        <% end %>
      </div>

      <div class="my-5">
        <%= form.label :title %>
        <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :description %>
        <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :status %>
        <%= form.select :status, options_for_select(["In Progress", "Completed"], task.status), class: "block mt-2 border-gray-300 rounded-md p-2" %>
      </div>


      <div class="inline-flex justify-end">
        <%= form.submit "Submit", class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium cursor-pointer" %>
      </div>

      <div>
        <%= link_to "Cancel", "#", data: {action: "click->taskhandler#removeModal"} %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= task.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= task.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= task.status %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this task", task, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this task', edit_task_path(task), data: {turbo_frame: "form"}, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= button_to 'Destroy this task', task_path(task), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>

    <hr class="mt-6">
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag 'form' do %>
  <div data-controller="taskhandler" data-action="turbo:submit-end->taskhandler#submitEnd" class="mx-auto md:w-2/3 w-full">
    <%= render partial: "form", locals: { task: @task, form_type_needed: "edit" } %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div>
    <%= turbo_frame_tag 'form' %>
  </div>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tasks</h1>
    <%= link_to 'New task', new_task_path, data: {turbo_frame: 'form'}, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="tasks" class="min-w-full">
    <%= render @tasks %>
  </div>
</div>

app/views/tasks/landing.html.erb
<%= turbo_frame_tag "modal" %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag 'form' do %>
  <div data-controller="taskhandler" data-action="turbo:submit-end->taskhandler#submitEnd" class="mx-auto md:w-2/3 w-full">
    <%= render partial: "form", locals: {task: @task, form_type_needed: "new"} %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @task %>

    <%= link_to 'Edit this task', edit_task_path(@task), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this task', task_path(@task), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to tasks', tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>